feat: allow for disabling changelog creation
ridedott/release-me-action pull request #430
Opened 2020-12-02 15:07 UTC by acazacu

This pull request adds an input parameter that allows for disabling generating a CHANGELOG.md file. In order to not break the current implementations, generating the CHANGELOG.md file remains enabled by default.

Resolves issues:
- https://github.com/ridedott/release-me-action/issues/410
- https://github.com/ridedott/release-me-action/issues/228 (explicitly related to the `@semantic-release/changelog` plugin)

2020-12-03 07:13 UTC, joachimroeleveld reviewed
Maybe we can disable it and enable it explicitly where it's needed? Seems there are not many places. @merlinnot do you know this?

2020-12-03 07:20 UTC, merlinnot requested changes
@acazacu We decided to pick that up specifically to follow [this](https://github.com/ridedott/release-me-action/issues/228#issuecomment-732802454) implementation proposal, which is needed in many `/ridedott` repositories.

2020-12-03 09:02 UTC, acazacu commented
> @acazacu We decided to pick that up specifically to follow [this](https://github.com/ridedott/release-me-action/issues/228#issuecomment-732802454) implementation proposal, which is needed in many `/ridedott` repositories.

Can you offer a few examples of what exactly is it that we need? I'm not really up to date with the shortcomings of the current implementation from our point of view.

2020-12-04 08:07 UTC, acazacu commented
> Maybe we can disable it and enable it explicitly where it's needed? Seems there are not many places. @merlinnot do you know this?

So far as I know, we use it in most repositories that we have.

2020-12-04 08:11 UTC, merlinnot reviewed
After the discussion we had with @acazacu we came to a conclusion that we'd like to keep a possibility of having Semantic abstracted, so that it's not necessary to configure plugins etc. manually, to have a simple way of covering "the 80%". We'll be exploring both additional options and a fully custom plugin configuration as well.

2020-12-04 08:11 UTC, merlinnot commented on README.md
> +      disable-generate-changelog: true
Maybe we can simplify a bit?

```suggestion
      disable-changelog: true
```

2020-12-04 08:12 UTC, merlinnot commented
> > Maybe we can disable it and enable it explicitly where it's needed? Seems there are not many places. @merlinnot do you know this?
> 
> So far as I know, we use it in most repositories that we have.

We use it basically everywhere, I think it became a de-facto standard, I'd say it's good to have it enabled by default.

2020-12-04 08:12 UTC, joachimroeleveld approved these changes

2020-12-04 08:27 UTC, merlinnot approved these changes

2020-12-04 08:27 UTC, merged